# Generated by Django 4.1.2 on 2022-12-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_rename_numapi_persondata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondata',
            old_name='description',
            new_name='birthdate',
        ),
    ]
