# Generated by Django 4.1.2 on 2022-12-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_rename_description_persondata_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondata',
            name='surname',
            field=models.CharField(default='NOT SET', max_length=100),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='birthdate',
            field=models.CharField(default='NOT SET', max_length=100),
        ),
    ]
