# Generated by Django 4.1.2 on 2022-12-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_persondata_surname_alter_persondata_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonNumerology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerology', models.CharField(default='NOT SET', max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.persondata')),
            ],
        ),
    ]
