# Generated by Django 4.1.2 on 2022-12-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_personnumerology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondata',
            old_name='birthdate',
            new_name='date',
        ),
    ]
